source              : .
destination         : ./_site
collections_dir     : .
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes

baseurl: "http://swiftmegaminds.tech/" 
url: "http://swiftmegaminds.tech/"
github_username: swift-megaminds


sass:
  sass_dir: _sass
collections:
  posts:
    output          : true
